### ISSUE TITLE
finger_joint.py

### ISSUE THREAD

**Issue by marmalodak** [SolidCode/SolidPython#31]
```
$ python finger_joint.py
Traceback (most recent call last):
  File "finger_joint.py", line 34, in <module>
    a = assembly()
  File "finger_joint.py", line 29, in assembly
    a = finger_joint( p, poly_sheet_thick=4.75, other_sheet_thick=4.75, joint_width=None, kerf=0.1)
NameError: global name 'p' is not defined
```

**Comment by etjones** [comment]
This file is version-cruft of an unfinished library function.  Just removed it, as I should have done a long time ago.  Thanks for pointing it out, and let me know if any of the files in `examples` give you a hard time.
